### ISSUE TITLE
USB2.0 USB Power limitation

### ISSUE THREAD

**Issue by tigerwang202** [easyvolts/EasyVolts_rev1#2]
Due to 500mA maximum current limitation from USB 2.0 specification, the Max output current  1A is impossible, unless using an auxiliary 5v power supply.

**Comment by easyvolts** [comment]
This is not correct. 1a current is reachable when EasyVolts is in stepDown mode (output voltage is <5v). For example at 1v8 output voltage 1a can be reached (max input power is 2.5w, output power at 1v8 can be 1.8w = 1v8*1a).

**Comment by tigerwang202** [comment]
So we need some current limitation method to make sure the VBus current doesn't exceed specification, maybe current monitor(like TI's INA180) connected to MCU's ADC channel?

**Comment by easyvolts** [comment]
It's already in the code. Software monitors current (by measuring a voltage on the shunt resistor) and starts reducing output voltage when current goes higher than the limit. The limit can be set by iXXX\r\n command over terminal. If the user tries to set too high power limit - it will be limited inside of the firmware to keep output power <=2.2w(don't remember the exact value). So power consumption from USB is limited. There is only one detail that could be improved - efficiency of the system is not the same for different output voltages, so it would be good to test efficiency in complete output voltage range to create a table that would specify max output power for each output voltage taking into account efficiency of the DCDC. This would guaranty that we will limit power consumption from USB at an appropriate level.
